name: Plexdrive

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Next step
        run: echo bye!
