name: Sample

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            emulator -list-avds
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - name: Next step
        run: echo bye!
